[general]
import = [
"~/.config/alacritty/themes/monokai_pro.toml"
]

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[env]
term = "xterm-256color"

[font]
size = 16

[font.bold]
family = "UDEV Gothic 35NFLG"
style = "Bold"

[font.bold_italic]
family = "UDEV Gothic 35NFLG"
style = "BoldItalic"

[font.italic]
family = "UDEV Gothic 35NFLG"
style = "Italic"

[font.normal]
family = "UDEV Gothic 35NFLG"
style = "Regular"

[window]
opacity = 0.85
decorations = "Transparent"
