version: '3'
services:
  neovim:
    build:
      context: ../../
      dockerfile: ./release/mynvim/Dockerfile
    volumes:
      - ../../rc/nvim:/root/.config/nvim
    working_dir: /root/.config/nvim
    tty: true
