[interpreters]
ps1 = { command = "pwsh.exe", args = ["-NoLogo"] }

[edit]
  command = "nvim"

[merge]
  command = "nvim"
  args = ["-d", "{{ "{{" }} .Destination {{ "}}" }}", "{{ "{{" }} .Source {{ "}}" }}", "{{ "{{" }} .Target {{ "}}" }}"]

[diff]
  pager = "delta"
  command = "delta"
  exclude = ["scripts"]
  args = ["--pager=0", "{{ "{{" }} .Destination {{ "}}" }}", "{{ "{{" }} .Target {{ "}}" }}"]