#!/bin/zsh
function __ftm_parse() {
    if (echo $1 | /usr/bin/grep -E "^\[alias\]" &>/dev/null); then
        project_name=${1:8}
        line=( `/usr/bin/cat $GHUX_ALIASES_PATH|/usr/bin/grep -E "${project_name}," | /usr/bin/cut -d',' -f2` )
        project_dir="$(eval echo ${line[1]})"
    elif (echo $1 | /usr/bin/grep -E "^\[.*\]" &>/dev/null); then
        project_dir="$(ghq root)"
        project_name="default"
    else
        project_dir=$(ghq root)/$1
        project_name=$(echo $project_dir | /usr/bin/rev | /usr/bin/awk -F \/ '{printf "%s", $1}' | /usr/bin/rev | /usr/bin/awk '{sub("\\.",""); print $0}')
    fi
    echo "${project_name},${project_dir}"
}

[[ -f "$HOME/.local/zsh_local/.zshenv" ]] && source "$HOME/.local/zsh_local/.zshenv"
