[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'sickill/vim-monokai'
hook_add = '''
colorscheme monokai
'''

[[plugins]]
repo = 'AlessandroYorba/Alduin'

[[plugins]]
repo = 'romainl/Apprentice'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['denite-git']
hook_add = '''
augroup My_Denite
    au!
    au FileType denite call my_denite#settings()
    au vimenter * call my_denite#openings()
augroup END

'''

[[plugins]]
repo = 'neoclide/denite-git'
hook_add = '''
augroup My_Denite_Git
    au!
    au vimenter * call my_denite_git#openings()
augroup END
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons', 'defx-git']
hook_add = '''
call my_defx#options()
augroup My_Defx
    au!
    au FileType defx call my_defx#settings()
augroup END
if argc()==0
    au vimenter * Defx
endif
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = "kristijanhusak/defx-git"

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'rhysd/committia.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
call my_lightline#options()
'''
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
function! s:on_lsp_buffer_enabled() abort
    if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
    nmap <buffer> gd <plug>(lsp-definition)
    nmap <buffer> gr <plug>(lsp-references)
    nmap <buffer> gi <plug>(lsp-implementation)
    nmap <buffer> gt <plug>(lsp-type-definition)
    nmap <buffer> <leader>rn <plug>(lsp-rename)
    nmap <buffer> [g <Plug>(lsp-previous-diagnostic)
    nmap <buffer> ]g <Plug>(lsp-next-diagnostic)
    nmap <buffer> K <plug>(lsp-hover)
    
    " refer to doc to add more commands
endfunction

augroup lsp_install
    au!
    " call s:on_lsp_buffer_enabled only for languages that has the server registered.
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
'''
depends = ['vim-lsp-settings']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merge = 0
