[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['plantuml']
hook_source = '''
let g:plantuml_executable_script='plantuml.sh'
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
depands = ['neosnippet.vim']
hook_source = '''
call my_neosnippet#settings()
let g:deoplete#enable_at_startup = 1
" For conceal markers.
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex', 'plaintex']

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['c', 'cpp']
hook_source = '''
let g:cpp_experimental_template_highlight = 1
let g:cpp_concepts_hilight = 1
let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'Shougo/neco-vim'
on_i = 1

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_cmd = 'help'
hook_add = '''
set helplang=ja,en
'''
