# This is a basic workflow to help you get started with Actions
name: chezmoi

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - name: install pkgs
        run: |
          iex "&{$(irm 'https://get.chezmoi.io/ps1')} -b '~/bin'"
          echo '$HOME/bin' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo $Env:PATH
          chezmoi init upnt
          echo '[System.Environment]::GetEnvironmentVariable("Path","Machine")' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo '[System.Environment]::GetEnvironmentVariable("Path","User")' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          chezmoi apply -v
        shell: powershell

  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install pkgs
        run: cd ~/.local/ && sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply upnt
