# This is a basic workflow to help you get started with Actions
name: chezmoi

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - name: Install packages
        run: |
          iex "&{$(irm 'https://get.chezmoi.io/ps1')} -b '$((Get-Item .).FullName)/bin'"
          $Env:PATH=$((Get-Item .).FullName)/bin;$Env:PATH
          ls $((Get-Item .).FullName)/bin
          chezmoi init upnt
          $Env:PATH='[System.Environment]::GetEnvironmentVariable("Path","Machine"); [System.Environment]::GetEnvironmentVariable("Path","User")'
          chezmoi apply -v
        shell: pwsh

  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
          PATH="$PATH; $HOME/.local/bin"
          ls $HOME/.local/bin
          chezmoi init
          chezmoi apply -v
