# This is a basic workflow to help you get started with Actions
name: chezmoi

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - name: Install winget
        uses: Cyberboss/install-winget@v1

      - name: Install chezmoi
        run: |
          $binDir = "$((Get-Item -Path '.').FullName)\bin"
          iex "&{$(irm 'https://get.chezmoi.io/ps1')} -b '$binDir'"
          echo '$binDir' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Initialize chezmoi
        run: |
          chezmoi init upnt
          winget install --allow-reboot --silent --accept-package-agreements --accept-source-agreements --disable-interactivity --id "dandavison.delta"
        shell: pwsh
        
      - name: Install packages
        run: chezmoi apply -v
        shell: pwsh

  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install chezmoi
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Initialize chezmoi
        run: chezmoi init upnt

      - name: Install packages
        run: chezmoi apply -v
