name: Installation

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ubuntu-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install chezmoi
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin

      - name: Initialize chezmoi
        run: |
          mkdir -p "$HOME"
          chezmoi init --no-tty --source "$GITHUB_WORKSPACE"
          chezmoi apply

  windows-test:
    permissions:
      contents: read
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: Install chezmoi
        shell: pwsh
        run: winget install --id twpayne.chezmoi -e --source winget
          --accept-source-agreements --accept-package-agreements --disable-interactivity

      - name: Install git
        shell: pwsh
        run: winget install Git.Git -s winget
          --accept-source-agreements --accept-package-agreements --disable-interactivity

      - name: Install packages
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path $env:HOME | Out-Null
          chezmoi init --no-tty --source "$env:GITHUB_WORKSPACE"
          chezmoi apply
