name: Installation

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ubuntu-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install chezmoi
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Initialize chezmoi
        run: chezmoi init --apply upnt

  windows-test:
    permissions:
      contents: read
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: Install chezmoi
        run: |
          $binDir = "$HOME\.local\bin"
          New-Item -ItemType Directory -Force -Path $binDir
          iex "&{$(irm 'https://get.chezmoi.io/ps1')} -b '$binDir'"
          echo "$binDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          if (-Not (Test-Path "$binDir\chezmoi.exe")) {
            throw "chezmoi installation failed!"
          }
        shell: pwsh

      - name: Install packages
        run: |
          winget install Git.Git -s winget
          [System.Environment]::GetEnvironmentVariable("Path","Machine") | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          [System.Environment]::GetEnvironmentVariable("Path","User") | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          git clone https://github.com/upnt/dotfiles "$HOME\.local\share\chezmoi"
          & "$HOME\.local\bin\chezmoi" init
        shell: pwsh
