# This is a basic workflow to help you get started with Actions
name: rcinstaller

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependences and apps
        run: choco install git

      - name: import configs
        run: .\setup\rcinstaller.ps1 1 2 3 4 5 6 7

  linux-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependences
        run: sudo apt-get update && sudo apt-get install curl git

      - name: import configs
        run: |
          chmod u+x ./setup/rcinstaller.sh
          ./setup/rcinstaller.sh 1 2 3 4 5 6 7
